"on":
  workflow_dispatch:
    inputs:
      pr_branch_from:
        description: Pull request head branch
        required: true
        type: string
      pr_branch_into:
        description: Pull request base branch
        required: true
        type: string
      pr_number:
        description: Pull request number
        required: true
        type: number
      pr_title:
        description: Pull request title
        required: true
        type: string
name: Porter Preview Environment
jobs:
  porter-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Create Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-preview-action@v0.2.0
      with:
        action_id: ${{ github.run_id }}
        cluster: "12"
        host: https://a1e0-103-98-78-26.ngrok.io
        installation_id: "26587911"
        namespace: pr-${{ github.event.inputs.pr_number }}-desafio-app
        pr_branch_from: ${{ github.event.inputs.pr_branch_from }}
        pr_branch_into: ${{ github.event.inputs.pr_branch_into }}
        pr_id: ${{ github.event.inputs.pr_number }}
        pr_name: ${{ github.event.inputs.pr_title }}
        project: "2"
        repo_name: desafio-app
        repo_owner: mnafees
        token: ${{ secrets.PORTER_TOKEN_2 }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.pr_number }}
