"on":
  workflow_dispatch:
    inputs:
      pr_branch_from:
        description: Pull request head branch
        required: true
        type: string
      pr_branch_into:
        description: Pull request base branch
        required: true
        type: string
      pr_number:
        description: Pull request number
        required: true
        type: number
      pr_title:
        description: Pull request title
        required: true
        type: string
name: Porter Preview Environment
jobs:
  porter-preview:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.pr_branch_from }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Create Porter preview env
        timeout-minutes: 30
        uses: porter-dev/porter-preview-action@v0.30.2
        with:
          action_id: ${{ github.run_id }}
          cluster: "34"
          host: https://dashboard.dev.getporter.dev
          installation_id: "23579915"
          namespace: pr-${{ github.event.inputs.pr_number }}-desafio-app
          pr_branch_from: ${{ github.event.inputs.pr_branch_from }}
          pr_branch_into: ${{ github.event.inputs.pr_branch_into }}
          pr_id: ${{ github.event.inputs.pr_number }}
          pr_name: ${{ github.event.inputs.pr_title }}
          project: "3"
          repo_name: desafio-app
          repo_owner: mnafees
          token: ${{ secrets.PORTER_TOKEN_3 }}
