"on":
  workflow_dispatch:
    inputs:
      pr_branch_from:
        description: Pull request head branch
        required: true
        type: string
      pr_branch_into:
        description: Pull request base branch
        required: true
        type: string
      pr_number:
        description: Pull request number
        required: true
        type: string
      pr_title:
        description: Pull request title
        required: true
        type: string
name: Porter Preview Environment
jobs:
  porter-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Create Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-preview-action@dev
      with:
        action_id: ${{ github.run_id }}
        cluster: "121"
        host: https://dashboard.staging.getporter.dev
        installation_id: "33095378"
        namespace: my-custom-branch-ns
        pr_branch_from: ${{ github.event.inputs.pr_branch_from }}
        pr_branch_into: ${{ github.event.inputs.pr_branch_into }}
        pr_id: ${{ github.event.inputs.pr_number }}
        pr_name: ${{ github.event.inputs.pr_title }}
        project: "29"
        repo_name: desafio-app
        repo_owner: mnafees
        token: ${{ secrets.PORTER_PREVIEW_PRODUCTION_29_121 }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.pr_number }}
